/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
