/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import myapp.util.Prompt;
import myapp.handler.BBQMenuHandler;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import myapp.vo.BBQProduct;
import myapp.handler.BBQMenuList;

public class App {

  BBQMenuList list = new BBQMenuList();

  public App() {
    // prepareMenu();
  }

  public static void main(String[] args) {
    // loadData();
    new App().execute();
    // saveData();
  }

  public void execute() {
    Prompt prompt = new Prompt();
    BBQMenuHandler menuHandler = new BBQMenuHandler(prompt, list);

    mainMenu: while (true) {
      printTitle();
      menuHandler.mainMenuShow();
      int mainMenuNum = Integer.parseInt(prompt.inputString(">").replaceAll("[^0-9]", ""));
      if (mainMenuNum > 0 && mainMenuNum < 13) {
        menuHandler.menuSelectShow(mainMenuNum);
      } else if (mainMenuNum == 0) {
        break;
      } else if (mainMenuNum == 13) {

      } else if (mainMenuNum == 14) {
        menuHandler.editSelectedMenu();
      } else if (mainMenuNum == 15) {
        menuHandler.orderedMenuListShow();
      } else {
        System.out.println("잘못 입력하셧습니다 ");
        System.out.println("\n\n");
        continue mainMenu;
      }

    }
  }

  private void loadData() {

  }

  private void saveData() {

  }

  static void printTitle() {
    System.out.println("----------------------------------------");
    System.out.println("        BBQ 메뉴 선택 프로그램         ");
    System.out.println("----------------------------------------");
  }
}
